[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"

[build.processing]
  skip = true

[[redirects]]
  from = "/blog/index.html"
  to = "/blog"
  status = 301
  force = true